/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import model from './acido.gltf'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(model)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials.carbon}
        position={[0.6, -2.93, 1.45]}
        scale={[-2.12, 4.66, 4.74]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials.bond}
        position={[-2.71, -5.19, 3.51]}
        rotation={[1.93, 0.56, 0.95]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials['bond.001']}
        position={[0.44, 0.27, 1.55]}
        rotation={[0.01, 0, 0]}
        scale={[0.37, 1.22, 0.27]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={nodes.Sphere002.material}
        position={[-5.38, -6.96, 4.33]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={nodes.Sphere004.material}
        position={[-3.3, -7.22, -3.8]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={nodes.Cylinder004.material}
        position={[-1.69, -5.44, -1.6]}
        rotation={[-2.25, -0.26, 0.43]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={nodes.Sphere003.material}
        position={[0.22, 2.71, 1.49]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials['bond.003']}
        position={[5.67, -3.15, 1.55]}
        rotation={[0, -0.01, -1.61]}
        scale={[0.37, 3.12, 0.28]}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={materials['carbon.001']}
        position={[10.92, -2.93, 1.45]}
        scale={[-2.12, 4.66, 4.74]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={nodes.Cylinder003.material}
        position={[14.57, -1.98, 1.57]}
        rotation={[1.54, 0.65, 1.63]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={materials['bond.005']}
        position={[13.9, -1.12, 1.51]}
        rotation={[1.54, 0.65, 1.63]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Sphere005.geometry}
        material={materials.oxigeno}
        position={[16.36, 0.31, 1.49]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={materials['bond.006']}
        position={[13.88, -5.19, 1.51]}
        rotation={[1.58, -0.65, -1.55]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Sphere006.geometry}
        material={materials['oxigeno.001']}
        position={[16.36, -6.61, 1.49]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={materials['bond.008']}
        position={[19.03, -6.49, 1.55]}
        rotation={[0, -0.01, -1.61]}
        scale={[0.37, 1.58, 0.28]}
      />
      <mesh
        geometry={nodes.Sphere007.geometry}
        material={materials['hidrogeno.003']}
        position={[21.72, -6.61, 1.49]}
        scale={[-1.18, 2.74, 2.7]}
      />
    </group>
  )
}

useGLTF.preload(model)
