/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import model from './caco3.gltf'


export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(model)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials.carbon}
        position={[0.6, -2.93, 0.74]}
        scale={[-2.12, 4.66, 4.74]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials.bond}
        position={[0.5, -2.56, 3.9]}
        rotation={[1.57, 0, 0]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials['bond.001']}
        position={[0.88, -0.46, -2.26]}
        rotation={[-0.95, 0, 0]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials['bond.002']}
        position={[0.57, -0.69, -7.43]}
        rotation={[-2.27, 0, 0]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={nodes.Sphere001.material}
        position={[0.6, 1.34, -4.9]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={nodes.Sphere002.material}
        position={[0.6, -3.18, 7.07]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={nodes.Sphere004.material}
        position={[0.63, -5.9, -4.45]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials['bond.004']}
        position={[0.57, -4.5, -7.2]}
        rotation={[-0.99, 0, 0]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={materials.calcio}
        position={[0.63, -2.94, -11.63]}
        scale={[-2.68, 6.99, 6.62]}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials['bond.006']}
        position={[0.88, -4.73, -1.6]}
        rotation={[-2.15, 0, 0.13]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={materials['bond.007']}
        position={[0.5, -3.57, 4.38]}
        rotation={[1.57, 0, 0]}
        scale={[0.37, 2.01, 0.27]}
      />
    </group>
  )
}

useGLTF.preload(model)
