/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import model from './ch4.gltf'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(model)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials.carbon}
        position={[0.6, 0.47, 1.23]}
        scale={[-2.12, 4.66, 4.74]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials.bond}
        position={[0.57, 4.68, 1.23]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials['bond.001']}
        position={[0.57, -1.77, 5.22]}
        rotation={[-1.02, 0, 0]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials['bond.002']}
        position={[0.57, -1.77, -2.77]}
        rotation={[-2.14, 0, 0]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials['bond.003']}
        position={[4.55, -1.77, 1.14]}
        rotation={[-1.56, 0.56, -1.59]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={materials.hidrogeno}
        position={[0.6, 7.89, 1.23]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={materials['hidrogeno.001']}
        position={[0.6, -3.18, 7.07]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={materials['hidrogeno.002']}
        position={[6.92, -3.18, 1.14]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={materials['hidrogeno.003']}
        position={[0.63, -3.18, -4.45]}
        scale={[-1.18, 2.74, 2.7]}
      />
    </group>
  )
}

useGLTF.preload(model)
