/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import model from './cloroformo.gltf'


export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(model)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials.carbon}
        position={[0.6, -2.93, 1.45]}
        scale={[-2.12, 4.66, 4.74]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials.bond}
        position={[0.5, -5.19, 4.67]}
        rotation={[2.23, 0, 0]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials['bond.001']}
        position={[0.88, 0.27, 1.55]}
        rotation={[0.01, 0, 0]}
        scale={[0.37, 1.22, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials['bond.002']}
        position={[-2.75, -5.21, 1.53]}
        rotation={[-0.28, -0.2, -0.88]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={nodes.Sphere001.material}
        position={[-5.05, -7.44, 1.61]}
        rotation={[-0.01, -0.01, 0.12]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={nodes.Sphere002.material}
        position={[0.29, -6.96, 6.79]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={nodes.Sphere004.material}
        position={[0.63, -7.22, -4.01]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials['bond.006']}
        position={[0.88, -5.44, -1.6]}
        rotation={[-2.29, 0, 0.13]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={materials['hidrogeno.002']}
        position={[0.63, 2.71, 1.49]}
        scale={[-1.18, 2.74, 2.7]}
      />
    </group>
  )
}

useGLTF.preload(model)
