/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import model from './co2.gltf'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(model)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.46, 1.31, 0.62]} rotation={[-2.37, 0.66, 2.89]} scale={[0.33, 0.21, 0.4]}>
        <mesh geometry={nodes.Sphere003.geometry} material={materials['oxigeno rojo']} />
        <mesh geometry={nodes.Sphere003_1.geometry} material={materials['carbon ']} />
        <mesh geometry={nodes.Sphere003_2.geometry} material={materials.bond} />
        <mesh geometry={nodes.Sphere003_3.geometry} material={materials['bond.001']} />
        <mesh geometry={nodes.Sphere003_4.geometry} material={materials['bond.002']} />
        <mesh geometry={nodes.Sphere003_5.geometry} material={materials['bond.004']} />
      </group>
    </group>
  )
}

useGLTF.preload(model)
