/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import model from './h2o.gltf'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(model)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} />
      <mesh geometry={nodes.Sphere_Sphere002.geometry} material={materials.oxigeno_rojo} />
      <mesh geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} />
      <mesh geometry={nodes.Sphere001_Sphere003.geometry} material={nodes.Sphere001_Sphere003.material} />
      <mesh geometry={nodes.Sphere002_Sphere004.geometry} material={nodes.Sphere002_Sphere004.material} />
    </group>
  )
}

useGLTF.preload(model)
