/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import model from './hno3.gltf'


export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(model)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials['carbon.001']}
        position={[0.6, -2.93, 1.45]}
        scale={[-2.12, 4.66, 4.74]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials.bond}
        position={[0.5, -4.78, 3.9]}
        rotation={[2.09, 0, 0]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials['bond.001']}
        position={[0.88, 1.12, 0.88]}
        rotation={[0.01, 0, 0]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials['bond.002']}
        position={[0.57, 1.15, 1.74]}
        rotation={[0.04, 0, 0]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={nodes.Sphere001.material}
        position={[0.6, 4.49, 1.37]}
        rotation={[-0.01, -0.01, 0.12]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={nodes.Sphere002.material}
        position={[0.29, -6.07, 6.79]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={nodes.Sphere004.material}
        position={[0.63, -5.9, -4.45]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials['bond.006']}
        position={[0.88, -4.73, -1.6]}
        rotation={[-2.15, 0, 0.13]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={materials['bond.007']}
        position={[0.5, -4.38, 9.47]}
        rotation={[0.88, 0, 0]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={materials.hidrogeno}
        position={[0.29, -2.75, 11.22]}
        scale={[-1.18, 2.74, 2.7]}
      />
    </group>
  )
}

useGLTF.preload(model)
