/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import model from './nh3.gltf'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(model)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[2.22, -0.72, -0.3]}
        rotation={[-0.79, 0.62, 1.38]}
        scale={[0.5, 1.55, 0.74]}
      />
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials.nitrogeno}
        position={[-0.09, 1.13, 0.6]}
        scale={[1.57, 1.55, 1.64]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[-2.4, -1.13, 0.86]}
        rotation={[1.46, 0.73, -1.63]}
        scale={[0.5, 1.55, 0.74]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[0.69, -0.9, 2.76]}
        rotation={[2.15, -0.02, -0.29]}
        scale={[0.5, 1.55, 0.74]}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={materials.hidrogeno}
        position={[-3.15, -1.86, 0.84]}
        rotation={[-0.01, 0, 0.04]}
        scale={[0.77, 0.72, 0.74]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={materials['hidrogeno.001']}
        position={[1.1, -1.86, 4.27]}
        rotation={[-0.01, 0, 0.04]}
        scale={[0.77, 0.72, 0.74]}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={materials['hidrogeno.002']}
        position={[4.03, -1.86, -0.85]}
        rotation={[-0.01, 0, 0.04]}
        scale={[0.77, 0.72, 0.74]}
      />
    </group>
  )
}

useGLTF.preload(model)
