/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import model from './nitrog.gltf'


export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(model)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials.nitrogeno}
        position={[0.6, 5.87, -6.77]}
        rotation={[1.09, 0, 0]}
        scale={[-2.12, 4.66, 4.74]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials.bond}
        position={[0.5, 3.86, -3.68]}
        rotation={[1.95, 0, 0]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials['bond.001']}
        position={[0.88, 4.42, -10.76]}
        rotation={[1.1, 0, 0]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials['bond.002']}
        position={[0.57, 3.6, -10.18]}
        rotation={[1.13, 0, 0]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={nodes.Sphere001.material}
        position={[0.6, 2.65, -13.31]}
        rotation={[1.08, -0.01, 0.12]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={nodes.Sphere002.material}
        position={[0.29, 2.88, -0.97]}
        rotation={[1.09, 0, 0]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={nodes.Sphere004.material}
        position={[0.63, 12.56, -5.77]}
        rotation={[1.09, 0, 0]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials['bond.006']}
        position={[0.88, 9.56, -6.31]}
        rotation={[0.31, 0, 0.13]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials['bond.008']}
        position={[0.5, 3.53, 2.28]}
        rotation={[1.34, 0, 0]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={materials.carbon}
        position={[0.6, 4.49, 6.6]}
        rotation={[1.09, 0, 0]}
        scale={[-2.12, 4.66, 4.74]}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={materials['bond.009']}
        position={[0.16, 4.26, 10.69]}
        rotation={[1.8, -0.01, -3.12]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Sphere005.geometry}
        material={materials['carbon.001']}
        position={[0.6, 3.39, 15.11]}
        rotation={[1.09, 0, 0]}
        scale={[-2.12, 4.66, 4.74]}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={materials['bond.010']}
        position={[0.5, 6.86, 4.22]}
        rotation={[2.29, 0, 0]}
        scale={[0.34, 1.57, 0.19]}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={materials['bond.011']}
        position={[0.5, 6.66, 8.64]}
        rotation={[0.74, -0.91, 3.11]}
        scale={[0.34, 1.57, 0.19]}
      />
      <mesh
        geometry={nodes.Sphere006.geometry}
        material={materials['hidrogeno.002']}
        position={[0.29, 7.96, 2.77]}
        rotation={[1.09, 0, 0]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Sphere007.geometry}
        material={materials['hidrogeno.001']}
        position={[0.29, 7.91, 9.77]}
        rotation={[1.09, 0, 0]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Cylinder008.geometry}
        material={materials['bond.012']}
        position={[0.43, 5.4, 18.21]}
        rotation={[0.92, -0.01, 0.12]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder009.geometry}
        material={materials['bond.013']}
        position={[-1.64, 3.15, 16.23]}
        rotation={[2.79, -1.14, -1.88]}
        scale={[0.34, 1.57, 0.19]}
      />
      <mesh
        geometry={nodes.Sphere008.geometry}
        material={materials['hidrogeno.003']}
        position={[-3.41, 3.23, 17.93]}
        rotation={[1.09, 0, 0]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Cylinder010.geometry}
        material={materials['bond.014']}
        position={[0.5, -1, 15.26]}
        rotation={[-0.02, 0, 0]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder014.geometry}
        material={materials['bond.018']}
        position={[-1.44, -6.69, 18.89]}
        rotation={[-0.55, 0.75, -0.71]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder012.geometry}
        material={materials['bond.016']}
        position={[-2.09, -6.68, 15.1]}
        rotation={[0.11, 0.01, -0.99]}
        scale={[0.34, 1.57, 0.19]}
      />
      <mesh
        geometry={nodes.Cylinder011.geometry}
        material={materials['bond.015']}
        position={[0.76, -4.48, 12.53]}
        rotation={[-1.45, 0.08, 3.1]}
        scale={[0.34, 1.57, 0.19]}
      />
      <mesh
        geometry={nodes.Sphere011.geometry}
        material={materials['carbon.002']}
        position={[0.76, -4.95, 15.46]}
        rotation={[-0.86, 0.9, -0.48]}
        scale={[-2.12, 4.66, 4.74]}
      />
      <mesh
        geometry={nodes.Sphere010.geometry}
        material={materials['hidrogeno.005']}
        position={[-3.73, -7.52, 15.15]}
        rotation={[-0.86, 0.9, -0.48]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Sphere009.geometry}
        material={materials['hidrogeno.004']}
        position={[0.65, -4.11, 10.87]}
        rotation={[-0.86, 0.9, -0.48]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Cylinder018.geometry}
        material={materials['bond.023']}
        position={[0.5, 9.95, 20.37]}
        rotation={[3.1, 0, 0]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder017.geometry}
        material={materials['bond.022']}
        position={[0.88, 16.66, 18.02]}
        rotation={[2.25, 0, 0]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder016.geometry}
        material={materials['bond.021']}
        position={[0.57, 15.79, 17.51]}
        rotation={[2.28, 0, 0]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder013.geometry}
        material={materials['bond.019']}
        position={[0.88, 14.66, 24.52]}
        rotation={[1.46, 0, 0.13]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Sphere015.geometry}
        material={materials['nitrogeno.001']}
        position={[0.6, 13.59, 20.96]}
        rotation={[2.24, 0, 0]}
        scale={[-2.12, 4.66, 4.74]}
      />
      <mesh
        geometry={nodes.Sphere014.geometry}
        material={nodes.Sphere014.material}
        position={[0.6, 18.28, 15.37]}
        rotation={[2.24, -0.01, 0.12]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Sphere013.geometry}
        material={nodes.Sphere013.material}
        position={[0.29, 7.08, 20.56]}
        rotation={[2.24, 0, 0]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Sphere012.geometry}
        material={nodes.Sphere012.material}
        position={[0.63, 15.37, 27.48]}
        rotation={[2.24, 0, 0]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Cylinder022.geometry}
        material={materials['bond.028']}
        position={[-2.94, -17.15, 23.87]}
        rotation={[1.95, 0, 0]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder021.geometry}
        material={materials['bond.027']}
        position={[-2.56, -16.59, 16.79]}
        rotation={[1.1, 0, 0]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder020.geometry}
        material={materials['bond.026']}
        position={[-2.86, -17.41, 17.37]}
        rotation={[1.13, 0, 0]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder015.geometry}
        material={materials['bond.024']}
        position={[-2.56, -11.45, 21.24]}
        rotation={[0.31, 0, 0.13]}
        scale={[0.37, 2.01, 0.27]}
      />
      <mesh
        geometry={nodes.Sphere019.geometry}
        material={materials['nitrogeno.002']}
        position={[-2.83, -15.14, 20.77]}
        rotation={[1.09, 0, 0]}
        scale={[-2.12, 4.66, 4.74]}
      />
      <mesh
        geometry={nodes.Sphere018.geometry}
        material={nodes.Sphere018.material}
        position={[-2.83, -18.36, 14.23]}
        rotation={[1.08, -0.01, 0.12]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Sphere017.geometry}
        material={nodes.Sphere017.material}
        position={[-3.15, -18.13, 26.57]}
        rotation={[1.09, 0, 0]}
        scale={[-1.18, 2.74, 2.7]}
      />
      <mesh
        geometry={nodes.Sphere016.geometry}
        material={nodes.Sphere016.material}
        position={[-2.8, -8.45, 21.78]}
        rotation={[1.09, 0, 0]}
        scale={[-1.18, 2.74, 2.7]}
      />
    </group>
  )
}

useGLTF.preload(model)
